- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg-agent

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      register: docker_gpg_key

    - name: Get the distribution codename
      shell: lsb_release -cs
      register: dist_codename
      changed_when: false

    - name: Set up the stable repository for Debian
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ dist_codename.stdout }} stable"
        state: present
      when: docker_gpg_key is changed

    - name: Install Docker Engine
      apt:
        name: docker-ce
        update_cache: yes
        state: latest

- name: Initialize Docker Swarm Manager
  hosts: swarm_manager
  become: yes
  tasks:
    - name: Initialize the swarm
      command: docker swarm init --advertise-addr 192.168.0.22
      ignore_errors: yes

    - name: Get Docker Swarm join token for workers
      shell: docker swarm join-token worker -q
      register: worker_join_token
      run_once: true

- name: Join Swarm Workers
  hosts: swarm_worker
  become: yes
  vars:
    worker_token: "{{ hostvars[groups['swarm_manager'][0]]['worker_join_token']['stdout'] }}"
  tasks:
    - name: Join the swarm as a worker
      command: docker swarm join --token {{ worker_token }} 192.168.0.22:2377

- name: Deploy web service in Docker Swarm
  hosts: swarm_manager
  become: yes
  tasks:
    - name: Create a web service
      command: docker service create --name nginx --publish 8080:80 --replicas 3 nginx
